### ISSUE TITLE
In environments other than Windows, "TransactionAsync" fails.

### ISSUE THREAD

**Issue by 7k8m** [DirectSQL/DirectSQL#1]
# Evidence of problem
* Failed in ubuntu
https://github.com/DirectSQL/DirectSQL/actions/runs/51139908
````
Run dotnet test --configuration Release
Test run for /home/runner/work/DirectSQL/DirectSQL/TestSqlLiteDatabase/bin/Release/netcoreapp3.1/TestSqlLiteDatabase.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SQLiteConnection'.
   at System.Data.SQLite.SQLiteConnection.CheckDisposed()
   at System.Data.SQLite.SQLiteConnection.get_State()
   at System.Data.SQLite.SQLiteTransactionBase.IsValid(Boolean throwError)
   at System.Data.SQLite.SQLiteTransactionBase.Dispose(Boolean disposing)
   at System.Data.SQLite.SQLiteTransaction.Dispose(Boolean disposing)
   at System.Data.Common.DbTransaction.Dispose()
   at DirectSQL.Database`5.TransactionAsync(C connection, AsyncSqlExecution`2 execute) in /home/runner/work/DirectSQL/DirectSQL/DirectSQL/Database.cs:line 413
   at TestSqlLiteDatabase.TransactionTest.<>c.<<TestTransactionAsync>b__1_0>d.MoveNext() in /home/runner/work/DirectSQL/DirectSQL/TestSqlLiteDatabase/TransactionTest.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

````

* Passed in Windows
https://github.com/DirectSQL/DirectSQL/actions/runs/51140335
````
Run dotnet test --configuration Release
Test run for D:\a\DirectSQL\DirectSQL\TestSqlLiteDatabase\bin\Release\netcoreapp3.1\TestSqlLiteDatabase.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Test Run Successful.
Total tests: 18
     Passed: 18
 Total time: 2.2834 Seconds
````

# One possibility
In .NET Core other than Windows, implementation of transaction might have some problem around async / await.
Something like disposing transaction, when thread suspended, might be happened inside dotnet. 😢

**Comment by 7k8m** [comment]
There are possibility of problem of library.
So tried Microsoft.Data.Sqlite instead of System.Data.SQLite.

* Failed in utbuntu
https://github.com/DirectSQL/DirectSQL/actions/runs/51597346
* Passed in Windows
https://github.com/DirectSQL/DirectSQL/actions/runs/51596835

**Comment by 7k8m** [comment]
This might have some thing to do with this.
https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/async

**Comment by 7k8m** [comment]
Finally, this was mistaken code in test. 
Fixed in next
7d6392f67a065f3fe8461eacf897572329d9e10c
